### ISSUE TITLE
docs of style-any-component shows incorret case

### ISSUE THREAD

**Issue by we125182** [v-vibe/vue-styled-components#6]
### Describe the bug

docs of style-any-component shows incorret case

### To reproduce

<img width="1270" alt="image" src="https://github.com/v-vibe/vue-styled-components/assets/17947588/414ca4ed-4b85-4a75-8eb9-7291d926b15a">
https://vue-styled-components.com/guide/basic/styling-any-component. it should be blue.

**Comment by akinocccc** [comment]
It should be a bug in the document. Normal debugging cannot reproduce it.

**Comment by akinocccc** [comment]
Got it, it's a problem with the order in which CSS is generated.
